workflows:
  ios-secure:
    name: iOS AppStore Build
    environment:
      groups:
        - app  # contains Encrypted_ISSUER_ID, KEY_ID, PRIVATE_KEY
      vars:
        APP_ID: "com.nejalagha.brightpath"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
