workflows:
  ios-secure:
    name: iOS AppStore Build
    environment:
      groups:
        - app  # contains CERTIFICATE_PASSWORD if needed
      ios_signing:
        provisioning_profiles:
          - brightpath_cert  # name matches your uploaded .mobileprovision
        certificates:
          - brightpath_cert  # name matches your uploaded .p12 certificate
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
