workflows:
  ios-secure:
    name: iOS App Store Build
    environment:
      groups:
        - app # contains CERTIFICATE_PASSWORD if needed
      ios_signing:
        certificates:
          - brightpath_cert
        provisioning_profiles:
          - brightpath_cert
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS release (no codesign)
        script: |
          flutter build ios --release --no-codesign
      - name: Archive iOS app
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release -archivePath $HOME/build/Runner.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/build/Runner.xcarchive -exportPath $HOME/build -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - build/*.ipa
      - build/**/*.dSYM.zip
