workflows:
  ios-secure:
    name: iOS AppStore Build
    environment:
      groups:
        - app  # Make sure this group contains: Encrypted_ISSUER_ID, Encrypted_KEY_ID, Encrypted_PRIVATE_KEY
      vars:
        APP_ID: "com.nejalagha.brightpath"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $APP_ID
        auth:
          app_store_connect_issuer_id: $Encrypted_ISSUER_ID
          app_store_connect_key_identifier: $Encrypted_KEY_ID
          app_store_connect_private_key: $Encrypted_PRIVATE_KEY
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS Archive
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release -archivePath $HOME/output/$XCODE_SCHEME.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/output/$XCODE_SCHEME.xcarchive -exportPath $HOME/output -exportOptionsPlist ExportOptions.plist
    artifacts:
      - $HOME/output/*.ipa
      - $HOME/output/*.dSYM.zip
