workflows:
  ios-secure:
    name: iOS AppStore Build
    environment:
      groups:
        - app  # contains Encrypted_ISSUER_ID, KEY_ID, PRIVATE_KEY
      vars:
        APP_ID: "com.nejalagha.brightpath"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $APP_ID
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          rm -f Podfile.lock
          pod repo update
          pod install --verbose
      - name: Build iOS Archive
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release -archivePath $HOME/output/$XCODE_SCHEME.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/output/$XCODE_SCHEME.xcarchive -exportPath $HOME/output -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - $HOME/output/*.ipa
      - $HOME/output/*.dSYM.zip
