workflows:
  ios-secure:
    name: iOS AppStore Build
    environment:
      groups:
        - app
      ios_signing:
        provisioning_profiles:
          - brightpath_cert
        certificates:
          - brightpath_cert
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS release (no code sign)
        script: |
          flutter build ios --release --no-codesign

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Archive iOS app
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $HOME/output/Runner.xcarchive \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $HOME/output/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $HOME/output

    artifacts:
      - $HOME/output/*.ipa
      - $HOME/output/*.dSYM.zip
